# Site settings
title: ボードゲームルールライブラリ
email: your-email@example.com
description: >-
  ボードゲームのルール和訳とサマリーシートを提供するライブラリサイトです。
  初心者から上級者まで、様々なボードゲームを楽しむための情報をお届けします。
baseurl: "/18xx-JP_rules-more" # GitHub Pagesの場合は "/18xx-JP_rules-more"
url: "https://satamoto7.github.io" # GitHub Pagesの場合は "https://satamoto7.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# SEO設定
lang: ja_JP
timezone: Asia/Tokyo

# Collections（将来の拡張用）
collections:
  games:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: "ja"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CHANGELOG.md
  - .gitignore